services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    container_name: app1
    restart: always
    env_file:
      - .env 
    environment:
      - NODE_ENV=production
    networks:
      - web